services:
  - type: web
    name: stayease-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        value: https://stay-ease-backend-n6e0.onrender.com/api
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
